'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Archivos
    Public Property id As Integer
    Public Property Num_documento As String
    Public Property documento As Byte()
    Public Property RUT As Byte()
    Public Property Tarjeta_profesional As Byte()
    Public Property Hoja_de_vida As Byte()
    Public Property Certificado_academico As Byte()
    Public Property Certificado_laboral As Byte()
    Public Property Certificado_bancario As Byte()
    Public Property Certificado_Eps As Byte()
    Public Property AFP As Byte()
    Public Property Antecedentes As Byte()
    Public Property Examen_ingreso As Byte()
    Public Property Otros As Byte()

    Public Overridable Property Hoja_de_vida1 As Hoja_de_vida

End Class
