'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class BancoHVEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BancoHVEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Archivos() As DbSet(Of Archivos)
    Public Overridable Property Certificado_laboral() As DbSet(Of Certificado_laboral)
    Public Overridable Property Colilla_pago() As DbSet(Of Colilla_pago)
    Public Overridable Property Comunicados() As DbSet(Of Comunicados)
    Public Overridable Property Contrato() As DbSet(Of Contrato)
    Public Overridable Property Cuenta_cobro() As DbSet(Of Cuenta_cobro)
    Public Overridable Property Departamentos() As DbSet(Of Departamentos)
    Public Overridable Property Documentos_nomina() As DbSet(Of Documentos_nomina)
    Public Overridable Property Hoja_de_vida() As DbSet(Of Hoja_de_vida)
    Public Overridable Property Ingresar() As DbSet(Of Ingresar)
    Public Overridable Property Liquidaciones() As DbSet(Of Liquidaciones)
    Public Overridable Property Municipios() As DbSet(Of Municipios)
    Public Overridable Property OtrosSi() As DbSet(Of OtrosSi)
    Public Overridable Property Prestamos() As DbSet(Of Prestamos)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property ValoresxAnio() As DbSet(Of ValoresxAnio)

End Class
