'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Certificado_laboral
    Public Property id As Integer
    Public Property Nume_documento As String
    Public Property Certificado_laboral1 As Byte()

    Public Overridable Property Hoja_de_vida As Hoja_de_vida

End Class
