'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Colilla_pago
    Public Property id As Integer
    Public Property id_colilla_empleado As String
    Public Property Numero_documento As String
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Salario_base As Decimal
    Public Property Fecha_inicial As Date
    Public Property Fecha_final As Date
    Public Property Basico As Decimal
    Public Property Aux_transporte As Decimal
    Public Property Hrs_diurnas As Decimal
    Public Property Hrs_nocturnas As Decimal
    Public Property Hrs_dominicales As Decimal
    Public Property Hrs_festivas As Decimal
    Public Property Total_Hrs As Decimal
    Public Property Rec_nocturno As Decimal
    Public Property Rec_dominical As Decimal
    Public Property Rec_festivo As Decimal
    Public Property Total_Rec As Decimal
    Public Property Incapacidades As Decimal
    Public Property Licencias As Decimal
    Public Property Otros_devengados As Nullable(Of Decimal)
    Public Property Descripcion_otros_dev As String
    Public Property Total_devengado As Decimal
    Public Property Salud As Decimal
    Public Property Pension As Decimal
    Public Property Otras_deducciones As Nullable(Of Decimal)
    Public Property Descripcion_otras_ded As String
    Public Property Retencion As Decimal
    Public Property Prestamos As Decimal
    Public Property Total_deducciones As Decimal
    Public Property Neto_pagar As Decimal

    Public Overridable Property Hoja_de_vida As Hoja_de_vida

End Class
