'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contrato
    Public Property id As Integer
    Public Property Nume_documento As String
    Public Property Contrato_laboral As Byte()
    Public Property Tipo_Contrato As String
    Public Property Actividad As String
    Public Property Cargo As String
    Public Property Por_concepto_de As String
    Public Property salario_base As Decimal
    Public Property tiempo_corte As Integer
    Public Property Inicio_contrato As Date
    Public Property Fin_contrato As Nullable(Of Date)

    Public Overridable Property Hoja_de_vida As Hoja_de_vida
    Public Overridable Property Cuenta_cobro As ICollection(Of Cuenta_cobro) = New HashSet(Of Cuenta_cobro)
    Public Overridable Property OtrosSi As ICollection(Of OtrosSi) = New HashSet(Of OtrosSi)

End Class
