'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cuenta_cobro
    Public Property id As Integer
    Public Property Numero_documento As String
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Salario_base As Decimal
    Public Property Fecha_inicial As Date
    Public Property Fecha_final As Date
    Public Property Basico As Decimal
    Public Property Contrato As Integer
    Public Property Concepto_de As String
    Public Property Otros_devengados As Nullable(Of Decimal)
    Public Property Descripcion_otros_dev As String
    Public Property Otras_deducciones As Nullable(Of Decimal)
    Public Property Descripcion_otras_ded As String
    Public Property Retencion As Decimal
    Public Property Prestamos As Decimal
    Public Property Neto_pagar As Decimal

    Public Overridable Property Contrato1 As Contrato
    Public Overridable Property Hoja_de_vida As Hoja_de_vida

End Class
