'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Departamentos
    Public Property id As Integer
    Public Property nombre As String
    Public Property codigo As Integer

    Public Overridable Property Hoja_de_vida As ICollection(Of Hoja_de_vida) = New HashSet(Of Hoja_de_vida)
    Public Overridable Property Municipios As ICollection(Of Municipios) = New HashSet(Of Municipios)

End Class
