'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Hoja_de_vida
    Public Property id As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Tipo_documento As String
    Public Property Numero_documento As String
    Public Property Fecha_expedicion As Date
    Public Property Lugar_expedicion As Integer
    Public Property Fecha_nacimiento As Date
    Public Property Lugar_nacimiento As Integer
    Public Property Telefono As String
    Public Property Celular As String
    Public Property Correo_electronico As String
    Public Property Estado_civil As String
    Public Property Ocupacion As String
    Public Property Departamento As Integer
    Public Property Ciudad As Integer
    Public Property direccion As String
    Public Property Numero_de_cuenta As String
    Public Property Banco As String
    Public Property Nombre_de_contacto As String
    Public Property Telefono_contacto As String
    Public Property EPS As String
    Public Property AFP As String
    Public Property ARL As String

    Public Overridable Property Archivos As Archivos
    Public Overridable Property Certificado_laboral As ICollection(Of Certificado_laboral) = New HashSet(Of Certificado_laboral)
    Public Overridable Property Colilla_pago As ICollection(Of Colilla_pago) = New HashSet(Of Colilla_pago)
    Public Overridable Property Comunicados As ICollection(Of Comunicados) = New HashSet(Of Comunicados)
    Public Overridable Property Contrato As ICollection(Of Contrato) = New HashSet(Of Contrato)
    Public Overridable Property Cuenta_cobro As ICollection(Of Cuenta_cobro) = New HashSet(Of Cuenta_cobro)
    Public Overridable Property Departamentos As Departamentos
    Public Overridable Property Municipios As Municipios
    Public Overridable Property Municipios1 As Municipios
    Public Overridable Property Municipios2 As Municipios
    Public Overridable Property Liquidaciones As ICollection(Of Liquidaciones) = New HashSet(Of Liquidaciones)
    Public Overridable Property Prestamos As ICollection(Of Prestamos) = New HashSet(Of Prestamos)

End Class
