'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Liquidaciones
    Public Property id As Integer
    Public Property Numero_documento As String
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Fecha_inicial As Date
    Public Property Fecha_final As Date
    Public Property Basico As Decimal
    Public Property Aux_transporte As Decimal
    Public Property Descripcion_prestacion As String
    Public Property Prima As Decimal
    Public Property Cesantias As Decimal
    Public Property Int_cesantias As Decimal
    Public Property Vacaciones As Decimal
    Public Property Total_liquidado As Decimal

    Public Overridable Property Hoja_de_vida As Hoja_de_vida

End Class
