'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Municipios
    Public Property id As Integer
    Public Property departamento_id As Integer
    Public Property codigo As Integer
    Public Property nombre As String

    Public Overridable Property Departamentos As Departamentos
    Public Overridable Property Hoja_de_vida As ICollection(Of Hoja_de_vida) = New HashSet(Of Hoja_de_vida)
    Public Overridable Property Hoja_de_vida1 As ICollection(Of Hoja_de_vida) = New HashSet(Of Hoja_de_vida)
    Public Overridable Property Hoja_de_vida2 As ICollection(Of Hoja_de_vida) = New HashSet(Of Hoja_de_vida)

End Class
