'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Prestamos
    Public Property id As Integer
    Public Property Num_documento As String
    Public Property Fecha_prestamo As Date
    Public Property Fecha_fin_prestamo As Date
    Public Property Metodo_pago As String
    Public Property Valor_prestamo As Decimal

    Public Overridable Property Hoja_de_vida As Hoja_de_vida

End Class
