'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ValoresxAnio
    Public Property Anio As Integer
    Public Property Salario_minimo As Decimal
    Public Property Aux_transporte As Decimal
    Public Property Salario_dia As Decimal
    Public Property Hora_diurna As Decimal
    Public Property Hora_nocturna As Decimal
    Public Property Hora_dominical As Decimal
    Public Property Hora_festivo As Decimal
    Public Property Recargo_nocturno As Decimal
    Public Property Recargo_dominical As Decimal
    Public Property Recargo_festivo As Decimal
    Public Property Salud As Decimal
    Public Property Pension As Decimal

End Class
